name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  xcode_16:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 🔍 Xcode Select
        run: |
          XCODE_PATH=`mdfind "kMDItemCFBundleIdentifier == 'com.apple.dt.Xcode' && kMDItemVersion = '16.*'" -onlyin /Applications | head -1`
          echo "DEVELOPER_DIR=$XCODE_PATH/Contents/Developer" >> $GITHUB_ENV
      - name: Version
        run: swift --version
      - name: Build
        run: swift test --enable-code-coverage --filter do_not_test
      - name: Test
        run: swift test --enable-code-coverage --skip-build
      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/FlyingFoxPackageTests.xctest/Contents/MacOS/FlyingFoxPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage_report.lcov

  xcode_15_4:
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  xcode_15_2:
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  linux_swift_5_10:
    runs-on: ubuntu-latest
    container: swift:5.10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  linux_swift_5_9:
    runs-on: ubuntu-latest
    container: swift:5.9
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  linux_swift_6_0:
    runs-on: ubuntu-latest
    container: swift:6.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  linux_swift_6_0_musl:
    runs-on: ubuntu-latest
    container: swift:6.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: SDK List Pre
        run: swift sdk list
      - name: Install SDK
        run: swift sdk install https://download.swift.org/swift-6.0.1-release/static-sdk/swift-6.0.1-RELEASE/swift-6.0.1-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz --checksum d4f46ba40e11e697387468e18987ee622908bc350310d8af54eb5e17c2ff5481
      - name: SDK List Post
        run: swift sdk list
      - name: Build
        run: swift build --swift-sdk x86_64-swift-linux-musl
